index:
   path: /
   controller: App\Controller\MediaController::index

list_media:
  path: list_media
  controller: App\Controller\MediaController::list

dynamic_media:
  path: dynamic_media/{media}
  controller: App\Controller\MediaController::generate