index:
   path: /
   controller: App\Controller\NotesController::index

list_notes:
  path: list_media
  controller: App\Controller\NotesController::list

add_notes:
  path: save_note/{note}
  methods: [POST]
  controller: App\Controller\NotesController::saveNotesAction